import type { AnalysisResult } from "@/types/analysis";

export const MOCK_RESULT: AnalysisResult = {
  module1: {
    title: "该SQL从订单表和用户表中汇总了近30天各品类销售额Top 10",
    businessPurpose: "统计近30天内不同品类的销售表现，找出销售额最高的前10个品类",
    dataSources: ["orders（订单表）", "customers（客户表）", "order_items（订单明细表）"],
    coreLogic: "将订单表与客户表、订单明细表关联，筛选近30天数据，按品类分组汇总销售额，取前10名",
    finalOutput: "品类名称 + 对应销售额的Top 10排行",
  },
  module2: {
    graphData: {
      nodes: [
        {
          id: "table:orders",
          type: "table",
          name: "orders",
          alias: "o",
          schema: "public",
          source: "physical",
          summary: "订单主表，记录每笔订单的基础信息",
          module: "主查询",
          dialectHints: [],
        },
        {
          id: "table:customers",
          type: "table",
          name: "customers",
          alias: "c",
          schema: "public",
          source: "physical",
          summary: "客户信息表",
          module: "主查询",
          dialectHints: [],
        },
        {
          id: "table:order_items",
          type: "table",
          name: "order_items",
          alias: "oi",
          schema: "public",
          source: "physical",
          summary: "订单明细表，记录每笔订单中每个商品的数量和金额",
          module: "主查询",
          dialectHints: [],
        },
        {
          id: "column:orders.order_id",
          type: "column",
          name: "order_id",
          tableId: "table:orders",
          dataType: "BIGINT",
          summary: "订单唯一标识",
          isPrimaryKey: true,
          isForeignKey: false,
          module: "主查询",
        },
        {
          id: "column:orders.created_at",
          type: "column",
          name: "created_at",
          tableId: "table:orders",
          dataType: "TIMESTAMP",
          summary: "订单创建时间",
          isPrimaryKey: false,
          isForeignKey: false,
          module: "主查询",
        },
        {
          id: "column:orders.customer_id",
          type: "column",
          name: "customer_id",
          tableId: "table:orders",
          dataType: "BIGINT",
          summary: "关联客户ID",
          isPrimaryKey: false,
          isForeignKey: true,
          module: "主查询",
        },
        {
          id: "column:customers.id",
          type: "column",
          name: "id",
          tableId: "table:customers",
          dataType: "BIGINT",
          summary: "客户唯一标识",
          isPrimaryKey: true,
          isForeignKey: false,
          module: "主查询",
        },
        {
          id: "column:customers.name",
          type: "column",
          name: "name",
          tableId: "table:customers",
          dataType: "VARCHAR",
          summary: "客户姓名",
          isPrimaryKey: false,
          isForeignKey: false,
          module: "主查询",
        },
        {
          id: "column:order_items.order_id",
          type: "column",
          name: "order_id",
          tableId: "table:order_items",
          dataType: "BIGINT",
          summary: "关联订单ID",
          isPrimaryKey: false,
          isForeignKey: true,
          module: "主查询",
        },
        {
          id: "column:order_items.category",
          type: "column",
          name: "category",
          tableId: "table:order_items",
          dataType: "VARCHAR",
          summary: "商品品类",
          isPrimaryKey: false,
          isForeignKey: false,
          module: "主查询",
        },
        {
          id: "column:order_items.amount",
          type: "column",
          name: "amount",
          tableId: "table:order_items",
          dataType: "DECIMAL",
          summary: "订单明细金额",
          isPrimaryKey: false,
          isForeignKey: false,
          module: "主查询",
        },
        {
          id: "function:SUM",
          type: "function",
          name: "SUM",
          normalizedName: "SUM",
          category: "aggregate",
          summary: "汇总函数：计算每个品类的销售总额",
          dialect: "mysql",
          isDialectSpecific: false,
          module: "主查询",
          teaching: {
            standardSyntax: "SUM(expr)",
            parameters: [
              { name: "expr", type: "数值表达式", required: true, description: "需要求和的目标列或计算表达式" },
            ],
            useCases: [
              "统计销售总额、收入汇总",
              "计算分组后的合计值",
              "与GROUP BY配合使用，按维度汇总",
            ],
            examples: [
              {
                title: "按品类汇总销售额",
                sql: "SELECT category, SUM(amount) AS total\nFROM order_items\nGROUP BY category",
                explanation: "对order_items表按category分组，计算每个品类的amount总和",
              },
            ],
            pitfalls: [
              "SUM会忽略NULL值，如果整列都是NULL则返回NULL而非0",
              "必须在GROUP BY中使用，否则会报错",
            ],
            difficulty: "basic",
          },
        },
        {
          id: "function:DATE_SUB",
          type: "function",
          name: "DATE_SUB",
          normalizedName: "DATE_SUB",
          category: "date",
          summary: "日期减法函数：计算30天前的日期",
          dialect: "mysql",
          isDialectSpecific: true,
          module: "主查询",
          teaching: {
            standardSyntax: "DATE_SUB(date, INTERVAL value unit)",
            parameters: [
              { name: "date", type: "日期", required: true, description: "基准日期" },
              { name: "value", type: "整数", required: true, description: "要减去的时间数值" },
              { name: "unit", type: "时间单位", required: true, description: "DAY/MONTH/YEAR等" },
            ],
            useCases: ["计算过去N天的数据", "生成时间范围的起始点", "数据回溯查询"],
            examples: [
              {
                title: "获取近30天数据",
                sql: "WHERE created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)",
                explanation: "筛选创建时间不早于30天前的记录",
              },
            ],
            pitfalls: [
              "这是MySQL专有函数，PG中应使用 NOW() - INTERVAL '30 days'",
              "INTERVAL后的单位用单数形式（DAY而非DAYS）",
            ],
            difficulty: "basic",
          },
        },
        {
          id: "function:COALESCE",
          type: "function",
          name: "COALESCE",
          normalizedName: "COALESCE",
          category: "conditional",
          summary: "空值处理函数：返回第一个非NULL的参数值",
          dialect: "mysql",
          isDialectSpecific: false,
          module: "主查询",
          teaching: null,
        },
      ],
      edges: [
        {
          id: "edge:orders.contains.order_id",
          type: "contains",
          sourceId: "table:orders",
          targetId: "column:orders.order_id",
          label: null,
          description: "orders 表包含 order_id 字段",
          executionOrder: null,
        },
        {
          id: "edge:orders.contains.created_at",
          type: "contains",
          sourceId: "table:orders",
          targetId: "column:orders.created_at",
          label: null,
          description: "orders 表包含 created_at 字段",
          executionOrder: null,
        },
        {
          id: "edge:orders.contains.customer_id",
          type: "contains",
          sourceId: "table:orders",
          targetId: "column:orders.customer_id",
          label: null,
          description: "orders 表包含 customer_id 字段",
          executionOrder: null,
        },
        {
          id: "edge:customers.contains.id",
          type: "contains",
          sourceId: "table:customers",
          targetId: "column:customers.id",
          label: null,
          description: "customers 表包含 id 字段",
          executionOrder: null,
        },
        {
          id: "edge:customers.contains.name",
          type: "contains",
          sourceId: "table:customers",
          targetId: "column:customers.name",
          label: null,
          description: "customers 表包含 name 字段",
          executionOrder: null,
        },
        {
          id: "edge:order_items.contains.order_id",
          type: "contains",
          sourceId: "table:order_items",
          targetId: "column:order_items.order_id",
          label: null,
          description: "order_items 表包含 order_id 字段",
          executionOrder: null,
        },
        {
          id: "edge:order_items.contains.category",
          type: "contains",
          sourceId: "table:order_items",
          targetId: "column:order_items.category",
          label: null,
          description: "order_items 表包含 category 字段",
          executionOrder: null,
        },
        {
          id: "edge:order_items.contains.amount",
          type: "contains",
          sourceId: "table:order_items",
          targetId: "column:order_items.amount",
          label: null,
          description: "order_items 表包含 amount 字段",
          executionOrder: null,
        },
        {
          id: "edge:orders.join.customers",
          type: "join",
          sourceId: "table:orders",
          targetId: "table:customers",
          label: "LEFT JOIN ON o.customer_id = c.id",
          description: "通过客户ID关联，获取客户姓名",
          executionOrder: 1,
        },
        {
          id: "edge:orders.join.order_items",
          type: "join",
          sourceId: "table:orders",
          targetId: "table:order_items",
          label: "INNER JOIN ON o.order_id = oi.order_id",
          description: "通过订单ID关联，获取订单明细",
          executionOrder: 2,
        },
        {
          id: "edge:uses.sum.amount",
          type: "compute_depends",
          sourceId: "function:SUM",
          targetId: "column:order_items.amount",
          label: "SUM(amount)",
          description: "SUM函数计算amount字段的总和",
          executionOrder: null,
        },
        {
          id: "edge:filter.created_at",
          type: "filter_depends",
          sourceId: "function:DATE_SUB",
          targetId: "column:orders.created_at",
          label: "WHERE created_at >= DATE_SUB(...)",
          description: "筛选近30天的订单数据",
          executionOrder: null,
        },
      ],
      metadata: {
        dialect: "mysql",
        statementTypes: ["SELECT"],
        tableCount: 3,
        columnCount: 7,
        functionCount: 3,
        cteCount: 0,
        subqueryCount: 0,
      },
    },
  },
  module3: [
    {
      nodeId: "table:orders",
      nodeSummary: "订单主表，存储每笔交易的核心信息",
      relatedNodes: [
        { nodeId: "table:customers", relationship: "通过 customer_id 与客户表关联", edgeType: "join" },
        { nodeId: "table:order_items", relationship: "通过 order_id 与订单明细关联", edgeType: "join" },
      ],
      globalContext: "该表是本SQL的主表（FROM来源），所有数据都以此为基础进行关联和筛选",
      teaching: null,
    },
    {
      nodeId: "function:SUM",
      nodeSummary: "求和聚合函数，计算品类销售额总和",
      relatedNodes: [
        { nodeId: "column:order_items.amount", relationship: "聚合 amount 字段的值", edgeType: "compute_depends" },
      ],
      globalContext: "在SELECT中与GROUP BY配合使用，按品类汇总计算总销售额作为最终排名依据",
      teaching: {
        standardSyntax: "SUM(expr)",
        parameters: [{ name: "expr", type: "数值表达式", required: true, description: "需要求和的目标列或计算表达式" }],
        useCases: ["统计销售总额、收入汇总", "计算分组后的合计值", "与GROUP BY配合使用，按维度汇总"],
        examples: [
          { title: "按品类汇总销售额", sql: "SELECT category, SUM(amount) AS total\nFROM order_items\nGROUP BY category", explanation: "对order_items表按category分组，计算每个品类的amount总和" },
        ],
        pitfalls: ["SUM会忽略NULL值，如果整列都是NULL则返回NULL而非0", "必须在GROUP BY中使用，否则会报错"],
        difficulty: "basic",
      },
    },
  ],
  module4: {
    joins: [
      {
        tables: ["orders", "customers"],
        joinType: "LEFT JOIN",
        condition: "o.customer_id = c.id",
        explanation: "以订单表为主表，左连接客户表获取客户姓名，即使客户信息缺失，订单数据仍会保留",
      },
      {
        tables: ["orders", "order_items"],
        joinType: "INNER JOIN",
        condition: "o.order_id = oi.order_id",
        explanation: "订单表与订单明细表内连接，只保留有明细的订单",
      },
    ],
    filters: [
      {
        condition: "o.created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)",
        location: "WHERE",
        explanation: "过滤出近30天内创建的订单，使用MySQL DATE_SUB函数做时间范围筛选",
        filterType: "range",
      },
    ],
    aggregations: [
      {
        groupByColumns: ["oi.category"],
        aggregateFunctions: ["SUM(oi.amount)"],
        explanation: "按商品品类分组，对每个品类的订单金额求和，作为Top 10排名的依据",
      },
    ],
    executionPriority: [
      {
        order: 1,
        operation: "FROM + JOIN",
        description: "orders作为主表，LEFT JOIN customers，INNER JOIN order_items",
        inputs: ["orders", "customers", "order_items"],
        outputs: ["三表关联的中间结果集"],
      },
      {
        order: 2,
        operation: "WHERE 筛选",
        description: "筛选 created_at 在近30天内的记录",
        inputs: ["中间结果集"],
        outputs: ["过滤后结果集"],
      },
      {
        order: 3,
        operation: "GROUP BY 聚合",
        description: "按 oi.category 分组，SUM(oi.amount) 计算品类总销售额",
        inputs: ["过滤后结果集"],
        outputs: ["聚合后的分组数据"],
      },
    ],
    dialectFeatures: [
      {
        feature: "DATE_SUB (MySQL专有)",
        explanation: "使用MySQL的DATE_SUB函数计算日期差，其他引擎需用不同方式",
        standardEquivalent: "PG: NOW() - INTERVAL '30 days', Presto: DATE_ADD('day', -30, NOW())",
      },
    ],
  },
};
